# TASK 1 - Netflix Data Cleaning & Preparation

Task Requirements

Import dataset using Pandas , 
Inspect the dataset , 
Identify missing values , 
Remove duplicate records , 
Standardize text columns , 
Convert date_added , 
Validate the cleaned dataset , 
Export the cleaned dataset

In [4]:
# importing necessary libraries

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
# loading the dataset

df = pd.read_csv(r"E:\Netflix_Data_Analysis\Datasets\Dataset.csv")

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully!
Number of rows: 8790
Number of columns: 10

In [6]:
# displaying the first 5 rows of the dataset

df.head(5)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [7]:
# displaying the last 5 rows of the dataset
df.tail(5)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [8]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [9]:
# Dataset shape

rows, columns = df.shape

print("Rows:", rows)
print("Columns:", columns)

Rows: 8790
Columns: 10

In [10]:
# Dataset column names

print("Column Names:")

for column in df.columns:
    print(column)

Column Names:
show_id
type
title
director
country
date_added
release_year
rating
duration
listed_in

In [11]:
# Checking for missing values in the dataset

missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [12]:
# Calculating the percentage of missing values in each column

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": missing_percentage
})

missing_table

              Missing Values  Percentage
show_id                    0         0.0
type                       0         0.0
title                      0         0.0
director                   0         0.0
country                    0         0.0
date_added                 0         0.0
release_year               0         0.0
rating                     0         0.0
duration                   0         0.0
listed_in                  0         0.0

In [13]:
# Checking for duplicate records in the dataset

duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 0

In [14]:
# Removing duplicate records from the dataset ( Even though dataset currently has zero duplicates, I have include the cleaning step.)

before_duplicates = len(df)

df = df.drop_duplicates()

after_duplicates = len(df)

print("Rows before removing duplicates:", before_duplicates)
print("Rows after removing duplicates:", after_duplicates)
print("Duplicates removed:", before_duplicates - after_duplicates)

Rows before removing duplicates: 8790
Rows after removing duplicates: 8790
Duplicates removed: 0

In [15]:
# Cleaning text columns by removing extra spaces

text_columns = [
    "type",
    "title",
    "director",
    "country",
    "rating",
    "duration",
    "listed_in"
]

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

print("Extra spaces removed from text columns.")

Extra spaces removed from text columns.

In [16]:
# Cleaning the "type" column by converting to title case

df["type"] = (    df["type"].str.strip().str.title())

print(df["type"].value_counts())

type
Movie      6126
Tv Show    2664
Name: count, dtype: int64

In [17]:
# Cleaning the "rating" column by converting to uppercase

df["rating"] = (df["rating"].str.strip().str.upper())

print("Unique Ratings:")
print(df["rating"].unique())

Unique Ratings:
<StringArray>
[   'PG-13',    'TV-MA',    'TV-PG',    'TV-14',    'TV-Y7',     'TV-Y',
       'PG',     'TV-G',        'R',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [18]:
# Cleaning the "date_added" column by converting to datetime format

df["date_added"] = pd.to_datetime(df["date_added"],errors="coerce")

print(df["date_added"].dtype)

datetime64[us]

In [19]:
# Extracting year, month, and month name from the "date_added" column

df["date_added_year"] = df["date_added"].dt.year
df["date_added_month"] = df["date_added"].dt.month
df["date_added_month_name"] = df["date_added"].dt.month_name()

print(df[[
    "date_added",
    "date_added_year",
    "date_added_month",
    "date_added_month_name"
]].head())

  date_added  date_added_year  date_added_month date_added_month_name
0 2021-09-25             2021                 9             September
1 2021-09-24             2021                 9             September
2 2021-09-24             2021                 9             September
3 2021-09-22             2021                 9             September
4 2021-09-24             2021                 9             September

In [20]:
# Checking the data type of the "release_year" column and its minimum and maximum values

print("Release Year Data Type:")
print(df["release_year"].dtype)

print("\nMinimum Release Year:")
print(df["release_year"].min())

print("\nMaximum Release Year:")
print(df["release_year"].max())

Release Year Data Type:
int64

Minimum Release Year:
1925

Maximum Release Year:
2021

In [21]:
# Cleaning the "duration" column by extracting the numeric value and converting it to float

df["duration_value"] = (df["duration"].str.extract(r"(\d+)").astype(float))

print(df[["duration", "duration_value"]].head(10))

    duration  duration_value
0     90 min            90.0
1   1 Season             1.0
2   1 Season             1.0
3     91 min            91.0
4    125 min           125.0
5  9 Seasons             9.0
6    104 min           104.0
7     87 min            87.0
8    127 min           127.0
9     76 min            76.0

In [22]:
# checking the unique values in the "type" column

print("Content Types:")
print(df["type"].unique())

Content Types:
<StringArray>
['Movie', 'Tv Show']
Length: 2, dtype: str

In [23]:
# checking the unique values in the "rating" column

print("Number of unique ratings:", df["rating"].nunique())

print("\nRatings:")
print(sorted(df["rating"].unique()))

Number of unique ratings: 14

Ratings:
['G', 'NC-17', 'NR', 'PG', 'PG-13', 'R', 'TV-14', 'TV-G', 'TV-MA', 'TV-PG', 'TV-Y', 'TV-Y7', 'TV-Y7-FV', 'UR']

In [24]:
# final check for missing values after cleaning

final_missing = df.isnull().sum()

print("Final Missing Values:")
print(final_missing)

Final Missing Values:
show_id                  0
type                     0
title                    0
director                 0
country                  0
date_added               0
release_year             0
rating                   0
duration                 0
listed_in                0
date_added_year          0
date_added_month         0
date_added_month_name    0
duration_value           0
dtype: int64

In [25]:
# final check for duplicate records after cleaning

final_duplicates = df.duplicated().sum()

print("Final duplicate records:", final_duplicates)

Final duplicate records: 0

In [26]:
# Final dataset information after cleaning

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Rows: 8790
Columns: 14

Column Names:
['show_id', 'type', 'title', 'director', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'date_added_year', 'date_added_month', 'date_added_month_name', 'duration_value']

Missing Values:
0

Duplicate Rows:
0

In [27]:
# displaying the first 5 rows of the cleaned dataset

df.head(5)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,date_added_year,date_added_month,date_added_month_name,duration_value
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021,9,September,90.0
1,s3,Tv Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021,9,September,1.0
2,s6,Tv Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021,9,September,1.0
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021,9,September,91.0
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021,9,September,125.0

In [28]:
# Exporting the cleaned dataset to a new CSV file

df.to_csv(
    "Netflix_Cleaned.csv",
    index=False
)

print("Cleaned dataset exported successfully!")
print("File name: Netflix_Cleaned.csv")

Cleaned dataset exported successfully!
File name: Netflix_Cleaned.csv

In [29]:
# Loading the cleaned dataset to verify the export

cleaned_df = pd.read_csv("Netflix_Cleaned.csv")

print("Cleaned dataset successfully loaded!")
print("Shape:", cleaned_df.shape)

cleaned_df.head()

Cleaned dataset successfully loaded!
Shape: (8790, 14)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,date_added_year,date_added_month,date_added_month_name,duration_value
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021,9,September,90.0
1,s3,Tv Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021,9,September,1.0
2,s6,Tv Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021,9,September,1.0
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021,9,September,91.0
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021,9,September,125.0